[2023-10-17T11:19:29.995+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [queued]>
[2023-10-17T11:19:30.003+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [queued]>
[2023-10-17T11:19:30.003+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-17T11:19:30.019+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-26 00:00:00+00:00
[2023-10-17T11:19:30.024+0000] {standard_task_runner.py:57} INFO - Started process 665 to run task
[2023-10-17T11:19:30.027+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-26T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpqjgsy5v0']
[2023-10-17T11:19:30.028+0000] {standard_task_runner.py:85} INFO - Job 120: Subtask waiting_for_data
[2023-10-17T11:19:30.068+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [running]> on host 238c1d4ff767
[2023-10-17T11:19:30.137+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-26T00:00:00+00:00'
[2023-10-17T11:19:30.148+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:19:30.148+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-17T11:19:30.149+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-17T11:19:30.149+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-17T11:19:30.158+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210426T000000, start_date=20231017T111929, end_date=20231017T111930
[2023-10-17T11:19:30.200+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-17T11:19:30.215+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T10:43:00.626+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [queued]>
[2023-10-18T10:43:00.638+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [queued]>
[2023-10-18T10:43:00.638+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T10:43:00.654+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-26 00:00:00+00:00
[2023-10-18T10:43:00.661+0000] {standard_task_runner.py:57} INFO - Started process 1628 to run task
[2023-10-18T10:43:00.664+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-26T00:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpajq1cw6o']
[2023-10-18T10:43:00.665+0000] {standard_task_runner.py:85} INFO - Job 119: Subtask waiting_for_data
[2023-10-18T10:43:00.716+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [running]> on host 2473b23ba069
[2023-10-18T10:43:00.793+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-26T00:00:00+00:00'
[2023-10-18T10:43:00.815+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-18T10:43:00.820+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210426T000000, start_date=20231018T104300, end_date=20231018T104300
[2023-10-18T10:43:00.833+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 119 for task waiting_for_data (The conn_id `fs_default` isn't defined; 1628)
[2023-10-18T10:43:00.880+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T10:43:00.910+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T11:17:37.004+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [queued]>
[2023-10-18T11:17:37.021+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [queued]>
[2023-10-18T11:17:37.021+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T11:17:37.042+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-26 00:00:00+00:00
[2023-10-18T11:17:37.049+0000] {standard_task_runner.py:57} INFO - Started process 515 to run task
[2023-10-18T11:17:37.054+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-26T00:00:00+00:00', '--job-id', '192', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmp4lgmw2k6']
[2023-10-18T11:17:37.055+0000] {standard_task_runner.py:85} INFO - Job 192: Subtask waiting_for_data
[2023-10-18T11:17:37.110+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [running]> on host 0e68aa52dfc7
[2023-10-18T11:17:37.256+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-26T00:00:00+00:00'
[2023-10-18T11:17:37.277+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-18T11:17:37.278+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-18T11:17:37.278+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-18T11:17:37.278+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-18T11:17:37.290+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210426T000000, start_date=20231018T111737, end_date=20231018T111737
[2023-10-18T11:17:37.353+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-18T11:17:37.392+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-19T12:42:55.759+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [queued]>
[2023-10-19T12:42:55.770+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [queued]>
[2023-10-19T12:42:55.771+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T12:42:55.789+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-26 00:00:00+00:00
[2023-10-19T12:42:55.795+0000] {standard_task_runner.py:57} INFO - Started process 1074 to run task
[2023-10-19T12:42:55.798+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-26T00:00:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpq9rh_k4p']
[2023-10-19T12:42:55.800+0000] {standard_task_runner.py:85} INFO - Job 208: Subtask waiting_for_data
[2023-10-19T12:42:55.859+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-26T00:00:00+00:00 [running]> on host 6f5df7fea6fd
[2023-10-19T12:42:55.937+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-26T00:00:00+00:00'
[2023-10-19T12:42:55.949+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-19T12:42:55.949+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-19T12:42:55.950+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-19T12:42:55.950+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-19T12:42:55.959+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210426T000000, start_date=20231019T124255, end_date=20231019T124255
[2023-10-19T12:42:55.980+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-19T12:42:56.065+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
