[2023-10-17T11:19:24.838+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [queued]>
[2023-10-17T11:19:24.845+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [queued]>
[2023-10-17T11:19:24.846+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-17T11:19:24.860+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-14 00:00:00+00:00
[2023-10-17T11:19:24.866+0000] {standard_task_runner.py:57} INFO - Started process 641 to run task
[2023-10-17T11:19:24.870+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-14T00:00:00+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmp81ji3iks']
[2023-10-17T11:19:24.871+0000] {standard_task_runner.py:85} INFO - Job 108: Subtask waiting_for_data
[2023-10-17T11:19:24.917+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [running]> on host 238c1d4ff767
[2023-10-17T11:19:25.016+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-14T00:00:00+00:00'
[2023-10-17T11:19:25.028+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:19:25.029+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-17T11:19:25.029+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-17T11:19:25.029+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-17T11:19:25.041+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210414T000000, start_date=20231017T111924, end_date=20231017T111925
[2023-10-17T11:19:25.086+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-17T11:19:25.148+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T10:42:54.676+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [queued]>
[2023-10-18T10:42:54.687+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [queued]>
[2023-10-18T10:42:54.687+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T10:42:54.724+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-14 00:00:00+00:00
[2023-10-18T10:42:54.732+0000] {standard_task_runner.py:57} INFO - Started process 1604 to run task
[2023-10-18T10:42:54.734+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-14T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmphxj9hpuf']
[2023-10-18T10:42:54.736+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask waiting_for_data
[2023-10-18T10:42:54.778+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [running]> on host 2473b23ba069
[2023-10-18T10:42:54.852+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-14T00:00:00+00:00'
[2023-10-18T10:42:54.867+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-18T10:42:54.870+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210414T000000, start_date=20231018T104254, end_date=20231018T104254
[2023-10-18T10:42:54.878+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 107 for task waiting_for_data (The conn_id `fs_default` isn't defined; 1604)
[2023-10-18T10:42:54.907+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T10:42:54.930+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T11:17:30.808+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [queued]>
[2023-10-18T11:17:30.816+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [queued]>
[2023-10-18T11:17:30.816+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T11:17:30.828+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-14 00:00:00+00:00
[2023-10-18T11:17:30.835+0000] {standard_task_runner.py:57} INFO - Started process 468 to run task
[2023-10-18T11:17:30.838+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-14T00:00:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmp6k3kkqgo']
[2023-10-18T11:17:30.839+0000] {standard_task_runner.py:85} INFO - Job 169: Subtask waiting_for_data
[2023-10-18T11:17:30.882+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [running]> on host 0e68aa52dfc7
[2023-10-18T11:17:30.980+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-14T00:00:00+00:00'
[2023-10-18T11:17:30.991+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-18T11:17:30.992+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-18T11:17:30.993+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-18T11:17:30.994+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-18T11:17:31.006+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210414T000000, start_date=20231018T111730, end_date=20231018T111731
[2023-10-18T11:17:31.050+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-18T11:17:31.084+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-19T12:22:10.608+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [queued]>
[2023-10-19T12:22:10.646+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [queued]>
[2023-10-19T12:22:10.647+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T12:22:10.680+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-14 00:00:00+00:00
[2023-10-19T12:22:10.694+0000] {standard_task_runner.py:57} INFO - Started process 677 to run task
[2023-10-19T12:22:10.707+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-14T00:00:00+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpsrediv3f']
[2023-10-19T12:22:10.710+0000] {standard_task_runner.py:85} INFO - Job 165: Subtask waiting_for_data
[2023-10-19T12:22:10.833+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-14T00:00:00+00:00 [running]> on host 6f5df7fea6fd
[2023-10-19T12:22:10.977+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-14T00:00:00+00:00'
[2023-10-19T12:22:11.014+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-19T12:22:11.014+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-19T12:22:11.015+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-19T12:22:11.015+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-19T12:22:11.033+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210414T000000, start_date=20231019T122210, end_date=20231019T122211
[2023-10-19T12:22:11.122+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-19T12:22:11.262+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
