[2023-10-17T11:19:23.161+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-10-17T11:19:23.174+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-10-17T11:19:23.174+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-17T11:19:23.201+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-11 00:00:00+00:00
[2023-10-17T11:19:23.210+0000] {standard_task_runner.py:57} INFO - Started process 635 to run task
[2023-10-17T11:19:23.213+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-11T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpgw8mnj0e']
[2023-10-17T11:19:23.214+0000] {standard_task_runner.py:85} INFO - Job 105: Subtask waiting_for_data
[2023-10-17T11:19:23.256+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [running]> on host 238c1d4ff767
[2023-10-17T11:19:23.326+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-11T00:00:00+00:00'
[2023-10-17T11:19:23.334+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:19:23.334+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-17T11:19:23.334+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-17T11:19:23.334+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-17T11:19:23.343+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210411T000000, start_date=20231017T111923, end_date=20231017T111923
[2023-10-17T11:19:23.386+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-17T11:19:23.401+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T10:42:54.283+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-10-18T10:42:54.290+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-10-18T10:42:54.291+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T10:42:54.302+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-11 00:00:00+00:00
[2023-10-18T10:42:54.307+0000] {standard_task_runner.py:57} INFO - Started process 1598 to run task
[2023-10-18T10:42:54.309+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-11T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmp6e8epsh_']
[2023-10-18T10:42:54.310+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask waiting_for_data
[2023-10-18T10:42:54.360+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [running]> on host 2473b23ba069
[2023-10-18T10:42:54.425+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-11T00:00:00+00:00'
[2023-10-18T10:42:54.442+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-18T10:42:54.446+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210411T000000, start_date=20231018T104254, end_date=20231018T104254
[2023-10-18T10:42:54.460+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 104 for task waiting_for_data (The conn_id `fs_default` isn't defined; 1598)
[2023-10-18T10:42:54.481+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T10:42:54.511+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T11:17:30.481+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-10-18T11:17:30.492+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-10-18T11:17:30.493+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T11:17:30.507+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-11 00:00:00+00:00
[2023-10-18T11:17:30.513+0000] {standard_task_runner.py:57} INFO - Started process 463 to run task
[2023-10-18T11:17:30.516+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-11T00:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpfsy2lrys']
[2023-10-18T11:17:30.517+0000] {standard_task_runner.py:85} INFO - Job 166: Subtask waiting_for_data
[2023-10-18T11:17:30.559+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [running]> on host 0e68aa52dfc7
[2023-10-18T11:17:30.633+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-11T00:00:00+00:00'
[2023-10-18T11:17:30.643+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-18T11:17:30.643+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-18T11:17:30.644+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-18T11:17:30.644+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-18T11:17:30.652+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210411T000000, start_date=20231018T111730, end_date=20231018T111730
[2023-10-18T11:17:30.688+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-18T11:17:30.716+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-19T12:22:09.411+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-10-19T12:22:09.427+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [queued]>
[2023-10-19T12:22:09.428+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T12:22:09.440+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-11 00:00:00+00:00
[2023-10-19T12:22:09.445+0000] {standard_task_runner.py:57} INFO - Started process 662 to run task
[2023-10-19T12:22:09.448+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-11T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpefyu9639']
[2023-10-19T12:22:09.449+0000] {standard_task_runner.py:85} INFO - Job 158: Subtask waiting_for_data
[2023-10-19T12:22:09.500+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-11T00:00:00+00:00 [running]> on host 6f5df7fea6fd
[2023-10-19T12:22:09.605+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-11T00:00:00+00:00'
[2023-10-19T12:22:09.619+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-19T12:22:09.620+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-19T12:22:09.620+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-19T12:22:09.620+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-19T12:22:09.633+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210411T000000, start_date=20231019T122209, end_date=20231019T122209
[2023-10-19T12:22:09.660+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-19T12:22:09.700+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
