[2023-10-17T11:19:22.953+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [queued]>
[2023-10-17T11:19:22.965+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [queued]>
[2023-10-17T11:19:22.966+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-17T11:19:22.981+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-09 00:00:00+00:00
[2023-10-17T11:19:22.989+0000] {standard_task_runner.py:57} INFO - Started process 632 to run task
[2023-10-17T11:19:22.992+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-09T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpolik5m_d']
[2023-10-17T11:19:22.994+0000] {standard_task_runner.py:85} INFO - Job 103: Subtask waiting_for_data
[2023-10-17T11:19:23.035+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [running]> on host 238c1d4ff767
[2023-10-17T11:19:23.126+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-09T00:00:00+00:00'
[2023-10-17T11:19:23.139+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:19:23.140+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-17T11:19:23.140+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-17T11:19:23.140+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-17T11:19:23.147+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210409T000000, start_date=20231017T111922, end_date=20231017T111923
[2023-10-17T11:19:23.166+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-17T11:19:23.203+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T10:42:51.852+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [queued]>
[2023-10-18T10:42:51.864+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [queued]>
[2023-10-18T10:42:51.864+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T10:42:51.878+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-09 00:00:00+00:00
[2023-10-18T10:42:51.885+0000] {standard_task_runner.py:57} INFO - Started process 1593 to run task
[2023-10-18T10:42:51.887+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-09T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmp59unu4ev']
[2023-10-18T10:42:51.887+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask waiting_for_data
[2023-10-18T10:42:51.933+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [running]> on host 2473b23ba069
[2023-10-18T10:42:52.049+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-09T00:00:00+00:00'
[2023-10-18T10:42:52.065+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-18T10:42:52.067+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210409T000000, start_date=20231018T104251, end_date=20231018T104252
[2023-10-18T10:42:52.076+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 102 for task waiting_for_data (The conn_id `fs_default` isn't defined; 1593)
[2023-10-18T10:42:52.099+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T10:42:52.123+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T11:17:26.368+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [queued]>
[2023-10-18T11:17:26.382+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [queued]>
[2023-10-18T11:17:26.383+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T11:17:26.405+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-09 00:00:00+00:00
[2023-10-18T11:17:26.414+0000] {standard_task_runner.py:57} INFO - Started process 448 to run task
[2023-10-18T11:17:26.419+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-09T00:00:00+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpkrvy4xu4']
[2023-10-18T11:17:26.420+0000] {standard_task_runner.py:85} INFO - Job 159: Subtask waiting_for_data
[2023-10-18T11:17:26.467+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [running]> on host 0e68aa52dfc7
[2023-10-18T11:17:26.565+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-09T00:00:00+00:00'
[2023-10-18T11:17:26.576+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-18T11:17:26.579+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-18T11:17:26.580+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-18T11:17:26.580+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-18T11:17:26.591+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210409T000000, start_date=20231018T111726, end_date=20231018T111726
[2023-10-18T11:17:26.633+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-18T11:17:26.664+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-19T12:22:09.064+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [queued]>
[2023-10-19T12:22:09.076+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [queued]>
[2023-10-19T12:22:09.077+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T12:22:09.093+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-09 00:00:00+00:00
[2023-10-19T12:22:09.101+0000] {standard_task_runner.py:57} INFO - Started process 658 to run task
[2023-10-19T12:22:09.104+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-09T00:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpwdz3lnl6']
[2023-10-19T12:22:09.106+0000] {standard_task_runner.py:85} INFO - Job 156: Subtask waiting_for_data
[2023-10-19T12:22:09.170+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-09T00:00:00+00:00 [running]> on host 6f5df7fea6fd
[2023-10-19T12:22:09.253+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-09T00:00:00+00:00'
[2023-10-19T12:22:09.264+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-19T12:22:09.264+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-19T12:22:09.265+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-19T12:22:09.265+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-19T12:22:09.289+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210409T000000, start_date=20231019T122209, end_date=20231019T122209
[2023-10-19T12:22:09.318+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-19T12:22:09.368+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
