[2023-10-17T11:19:30.217+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [queued]>
[2023-10-17T11:19:30.228+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [queued]>
[2023-10-17T11:19:30.228+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-17T11:19:30.268+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-28 00:00:00+00:00
[2023-10-17T11:19:30.274+0000] {standard_task_runner.py:57} INFO - Started process 669 to run task
[2023-10-17T11:19:30.277+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-28T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpifxw7bwa']
[2023-10-17T11:19:30.278+0000] {standard_task_runner.py:85} INFO - Job 122: Subtask waiting_for_data
[2023-10-17T11:19:30.329+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [running]> on host 238c1d4ff767
[2023-10-17T11:19:30.406+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-28T00:00:00+00:00'
[2023-10-17T11:19:30.415+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:19:30.416+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-17T11:19:30.416+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-17T11:19:30.416+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-17T11:19:30.423+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210428T000000, start_date=20231017T111930, end_date=20231017T111930
[2023-10-17T11:19:30.449+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-17T11:19:30.462+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T10:43:00.896+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [queued]>
[2023-10-18T10:43:00.907+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [queued]>
[2023-10-18T10:43:00.908+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T10:43:00.971+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-28 00:00:00+00:00
[2023-10-18T10:43:00.976+0000] {standard_task_runner.py:57} INFO - Started process 1632 to run task
[2023-10-18T10:43:00.979+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-28T00:00:00+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpmykt6xbb']
[2023-10-18T10:43:00.980+0000] {standard_task_runner.py:85} INFO - Job 121: Subtask waiting_for_data
[2023-10-18T10:43:01.022+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [running]> on host 2473b23ba069
[2023-10-18T10:43:01.079+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-28T00:00:00+00:00'
[2023-10-18T10:43:01.094+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-18T10:43:01.097+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210428T000000, start_date=20231018T104300, end_date=20231018T104301
[2023-10-18T10:43:01.106+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 121 for task waiting_for_data (The conn_id `fs_default` isn't defined; 1632)
[2023-10-18T10:43:01.151+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T10:43:01.179+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T11:17:37.769+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [queued]>
[2023-10-18T11:17:37.785+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [queued]>
[2023-10-18T11:17:37.786+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T11:17:37.797+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-28 00:00:00+00:00
[2023-10-18T11:17:37.803+0000] {standard_task_runner.py:57} INFO - Started process 531 to run task
[2023-10-18T11:17:37.805+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-28T00:00:00+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmptkpsc97i']
[2023-10-18T11:17:37.806+0000] {standard_task_runner.py:85} INFO - Job 196: Subtask waiting_for_data
[2023-10-18T11:17:37.849+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [running]> on host 0e68aa52dfc7
[2023-10-18T11:17:37.926+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-28T00:00:00+00:00'
[2023-10-18T11:17:37.942+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-18T11:17:37.945+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-18T11:17:37.945+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-18T11:17:37.945+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-18T11:17:37.956+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210428T000000, start_date=20231018T111737, end_date=20231018T111737
[2023-10-18T11:17:38.018+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-18T11:17:38.058+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-19T12:42:56.284+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [queued]>
[2023-10-19T12:42:56.320+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [queued]>
[2023-10-19T12:42:56.320+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T12:42:56.338+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-04-28 00:00:00+00:00
[2023-10-19T12:42:56.345+0000] {standard_task_runner.py:57} INFO - Started process 1085 to run task
[2023-10-19T12:42:56.349+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-04-28T00:00:00+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmps3hfndco']
[2023-10-19T12:42:56.350+0000] {standard_task_runner.py:85} INFO - Job 213: Subtask waiting_for_data
[2023-10-19T12:42:56.416+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-04-28T00:00:00+00:00 [running]> on host 6f5df7fea6fd
[2023-10-19T12:42:56.527+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-04-28T00:00:00+00:00'
[2023-10-19T12:42:56.538+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-19T12:42:56.538+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-19T12:42:56.539+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-19T12:42:56.539+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-19T12:42:56.549+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210428T000000, start_date=20231019T124256, end_date=20231019T124256
[2023-10-19T12:42:56.615+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-19T12:42:56.663+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
