[2023-10-17T11:19:35.735+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [queued]>
[2023-10-17T11:19:35.741+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [queued]>
[2023-10-17T11:19:35.742+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-17T11:19:35.751+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-05-14 00:00:00+00:00
[2023-10-17T11:19:35.757+0000] {standard_task_runner.py:57} INFO - Started process 699 to run task
[2023-10-17T11:19:35.759+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-05-14T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpoe1lprqn']
[2023-10-17T11:19:35.760+0000] {standard_task_runner.py:85} INFO - Job 138: Subtask waiting_for_data
[2023-10-17T11:19:35.807+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [running]> on host 238c1d4ff767
[2023-10-17T11:19:35.869+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-14T00:00:00+00:00'
[2023-10-17T11:19:35.875+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-17T11:19:35.875+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-17T11:19:35.876+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-17T11:19:35.876+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-17T11:19:35.882+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210514T000000, start_date=20231017T111935, end_date=20231017T111935
[2023-10-17T11:19:35.931+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-17T11:19:35.958+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T10:43:10.444+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [queued]>
[2023-10-18T10:43:10.452+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [queued]>
[2023-10-18T10:43:10.452+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T10:43:10.463+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-05-14 00:00:00+00:00
[2023-10-18T10:43:10.467+0000] {standard_task_runner.py:57} INFO - Started process 1662 to run task
[2023-10-18T10:43:10.469+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-05-14T00:00:00+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpmy8yvsag']
[2023-10-18T10:43:10.470+0000] {standard_task_runner.py:85} INFO - Job 137: Subtask waiting_for_data
[2023-10-18T10:43:10.504+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [running]> on host 2473b23ba069
[2023-10-18T10:43:10.558+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-14T00:00:00+00:00'
[2023-10-18T10:43:10.569+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/filesystem.py", line 61, in poke
    hook = FSHook(self.fs_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/filesystem.py", line 38, in __init__
    conn = self.get_connection(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `fs_default` isn't defined
[2023-10-18T10:43:10.571+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210514T000000, start_date=20231018T104310, end_date=20231018T104310
[2023-10-18T10:43:10.578+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 137 for task waiting_for_data (The conn_id `fs_default` isn't defined; 1662)
[2023-10-18T10:43:10.601+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-18T10:43:10.629+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-18T11:43:31.126+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [queued]>
[2023-10-18T11:43:31.139+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [queued]>
[2023-10-18T11:43:31.140+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-18T11:43:31.160+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-05-14 00:00:00+00:00
[2023-10-18T11:43:31.170+0000] {standard_task_runner.py:57} INFO - Started process 988 to run task
[2023-10-18T11:43:31.176+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-05-14T00:00:00+00:00', '--job-id', '226', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpzwn_xnlw']
[2023-10-18T11:43:31.180+0000] {standard_task_runner.py:85} INFO - Job 226: Subtask waiting_for_data
[2023-10-18T11:43:31.268+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [running]> on host 0e68aa52dfc7
[2023-10-18T11:43:31.429+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-14T00:00:00+00:00'
[2023-10-18T11:43:31.454+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-18T11:43:31.454+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-18T11:43:31.455+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-18T11:43:31.455+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-18T11:43:31.499+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210514T000000, start_date=20231018T114331, end_date=20231018T114331
[2023-10-18T11:43:31.575+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-18T11:43:31.664+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-10-19T12:44:26.774+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [queued]>
[2023-10-19T12:44:26.789+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [queued]>
[2023-10-19T12:44:26.790+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-19T12:44:26.806+0000] {taskinstance.py:1382} INFO - Executing <Task(FileSensor): waiting_for_data> on 2021-05-14 00:00:00+00:00
[2023-10-19T12:44:26.825+0000] {standard_task_runner.py:57} INFO - Started process 1199 to run task
[2023-10-19T12:44:26.828+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'copy_tranform_to_mongo', 'waiting_for_data', 'scheduled__2021-05-14T00:00:00+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/file_***-mongo.py', '--cfg-path', '/tmp/tmpjw4u33es']
[2023-10-19T12:44:26.838+0000] {standard_task_runner.py:85} INFO - Job 262: Subtask waiting_for_data
[2023-10-19T12:44:26.923+0000] {task_command.py:416} INFO - Running <TaskInstance: copy_tranform_to_mongo.waiting_for_data scheduled__2021-05-14T00:00:00+00:00 [running]> on host 6f5df7fea6fd
[2023-10-19T12:44:27.100+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='copy_tranform_to_mongo' AIRFLOW_CTX_TASK_ID='waiting_for_data' AIRFLOW_CTX_EXECUTION_DATE='2021-05-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2021-05-14T00:00:00+00:00'
[2023-10-19T12:44:27.116+0000] {base.py:73} INFO - Using connection ID 'fs_default' for task execution.
[2023-10-19T12:44:27.116+0000] {filesystem.py:64} INFO - Poking for file /opt/in/tiktok_google_play_reviews.csv
[2023-10-19T12:44:27.120+0000] {filesystem.py:69} INFO - Found File /opt/in/tiktok_google_play_reviews.csv last modified: 20220405221612
[2023-10-19T12:44:27.120+0000] {base.py:287} INFO - Success criteria met. Exiting.
[2023-10-19T12:44:27.154+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=copy_tranform_to_mongo, task_id=waiting_for_data, execution_date=20210514T000000, start_date=20231019T124426, end_date=20231019T124427
[2023-10-19T12:44:27.215+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-19T12:44:27.277+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
